### ISSUE TITLE
[Feature request] Auto export/import option

### ISSUE THREAD

**Issue by darwin67** [Its-treason/insomnia-plugin-git-integration#6]
Hi, thanks for creating the integration.

Personally, I like your approach more than the one that comes with the project. :)

As someone who mainly handles `git` related operations in the terminal, it would be great to have an auto export/import option, so diffs will automatically show up when changes are made, or reflected on Insomnia when branches changed.

There are definitely questions about how to handle conflicts but that can be a separate discussion.

**Comment by Its-treason** [comment]
Greetings, thanks for your idea, and I'm glad you like the project.

I think auto exporting project files should be an easy thing to do. 

But importing will be more difficult, because Insomnia must be restarted for an import. Maybe with a dialog confirming the Import & restart.

I'll look into your idea in the next few days! Thanks!

**Comment by darwin67** [comment]
Oh I was actually thinking on a collection level and not the project level.
~~Does it need to be reloaded even on a collection level?~~

Just gave it a try and it did restart the app even for a collection... :thinking: 
I think a dialog confirming the import is good then.
